#!/bin/bash

unameOut="$(uname -s)"
case "${unameOut}" in
    Linux*)     az_cmd=az;;
    CYGWIN*)    az_cmd=az.cmd;;
    MINGW*)     az_cmd=az.cmd;;
    Darwin*)    az_cmd=az;;
    *)          echo "Sorry, your OS is probably unsupported"; exit 5
esac

if [ "$az_cmd" == "az" ]; then
	if [ ! -x "$(which az)" ]; then print_missing_tool az; fi
elif [ "$az_cmd" == "az.cmd" ]; then
	if ! where az.cmd &>/dev/null; then print_missing_tool az.cmd; fi
fi

function aksver() {
	$az_cmd aks list --query '[].[name, kubernetesVersion]'
}

# Checking if owerwrite flag is set
while [ -n "$1" ]; do
	case "$1" in 
		"-f")
		FORCE="--overwrite-existing"
		;;
		"-q")
		shift
		QUERY=$1
		;;
		"--")
		shift
		break
		;;
		*)
		;;
	esac
	shift
done


# Constructing JSON from input arguments array
if [ ${#@} -gt 0 ]; then
	SUBS=("$@")
fi

# Getting the list of subscriptions

[ -z "$SUBS" ] && SUBS=$($az_cmd account list --query '[].name' -o tsv)

for subscription in ${SUBS}; do 
	# Setting the subscription
	$az_cmd account set -s "${subscription}"
	if [ -n "$QUERY" ]; then
		$QUERY
	else
		# Getting the list of AKSes
		$az_cmd aks list --query "[].[name,resourceGroup]" -o tsv | while read AKS RG; do
			# Merging the credentials per AKS
			if $az_cmd aks get-credentials --name "$AKS" --resource-group "$RG" $FORCE &>/dev/null; then
				echo "Successfully merged $AKS into Kube-config"
			else
				echo "$AKS merge failed"
			fi
		done
	fi
done
