#!/bin/bash
for tool in jq az; do 
	if [ ! -x "$(which $tool)" ]; then
		echo "You'll need $tool tool in order this script to work."
		echo
		echo "Please install it with appropriate way for your system!"
		echo
		exit 1
	fi
done

# Checking if owerwrite flag is set
if [ "$1" == "-f" ]; then
	FORCE="--overwrite-existing"
	shift
fi

# Constructing JSON from input arguments array
if [ ${#@} -gt 0 ]; then
	x=("$@")
	JSON=$(printf '%s\n' "${x[@]}" | jq -R . | jq -s .)
fi

# Getting the list of subscriptions

[ -z "$JSON" ] && JSON=$(az account list --query '[].name')
length=$(jq -r '. | length' <<<$JSON)


for (( i = 0; i <= length - 1; i++ )); do 
	# Setting the subscription
	az account set -s "$(jq -r ".[$i]" <<<$JSON)"
	# Getting the list of AKSes
	JSON2=$(az aks list --query "[].[name,resourceGroup]")
	length2=$(jq -r '. | length' <<<$JSON2)
	for (( j = 0; j <= length2 - 1; j++ )); do
		AKS=$(jq -r ".[$j][0]" <<<$JSON2)
		RG=$(jq -r ".[$j][1]" <<<$JSON2)
		# Merging the credentials per AKS
		if az aks get-credentials --name "$AKS" --resource-group "$RG" $FORCE &>/dev/null; then
			echo "Successfully merged $AKS into Kube-config"
		else
			echo "$AKS merge failed"
		fi
	done
done
